services:
  elasticsearch:
    image: elasticsearch:8.10.3
    container_name: es810
    restart: always
    volumes:
      - elastic8-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - es_net

  papa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    links:
      - elasticsearch
    ports:
      - "732:8000"
    networks:
      - es_net

volumes:
  elastic8-data:
    driver: local

networks:
  es_net:
    driver: bridge
